from flask import Flask, request, jsonify
import json
from index import tokenize

app = Flask(__name__)

# Load the inverted index from the file generated by index.py
with open('index.json', 'r', encoding='utf-8') as f:
    inverted_index = json.load(f)


@app.route('/search', methods=['GET'])
def search():
    query = request.args.get('query', '')
    if not query:
        return jsonify({"error": "No search term provided"}), 400

    query_tokens = tokenize(query)
    results = []

    # Search the inverted index
    for term, (freq, doc_ids) in inverted_index.items():
        if any(query_token in term for query_token in query_tokens):
            results.append({
                'term': term,
                'frequency': freq,
                'documents': doc_ids
            })

    if not results:
        return jsonify({"error": "No results found for the query"}), 404

    return jsonify({"results": results})


if __name__ == "__main__":
    app.run(debug=True)
